### ISSUE TITLE
Can't change engine sound on default acf engines

### ISSUE THREAD

**Issue by Nwhis** [bouletmarc/ACF_CustomMod#9]
I just remembered another issue that I found a few days ago (before the most recent update, wouldn't be caused by it).
The ACF Sound Replacer (and the custom variant) both do not support the default ACF engines.
Everything works fine on engines spawned with the custom menu, but not default.
Attempting to use either tool on an engine spawned with the default menu tool gives this error:
"acf_engine is not supported by the sound replacer!"
I think it's overwriting some code in the default replacer so then neither of them work on acf_engine; that is, if the custom sound replacer doesn't work for acf_engine, which I'm pretty sure it does.

**Comment by bouletmarc** [comment]
I'm currently working on this update issues list, the update will take a little longer to be out, but the issue was in the update list, and it will be sorted out. It's the 3rd and 6th, and your last issues request was the 1st. If you have others issue, reply to this post, I will let it open until the update arent out. Thank you very much again
1. Fix Engine Maker Dupe Error
2. Fix Somes Battery Models Interfering with some FuelTank Models
3. Fix Sound Tool Custom Interfering with Original Sound Tool
4. Fix a little Clutch Bug manual gearbox
5. Fix Engine sound doesnt die when running out of fuel
6. Add Original ACF Entities to Sound Tool Custom
7. Add PulseJet to Engine Maker
8. Add A Little more Torque when 'Idling' on Manual Gearboxes
9. Remove PulseJet 'Override' wire inputs

**Comment by bouletmarc** [comment]
Closing this issue, since the update are out and all reported issues are fixed back, thank you
